name: Build & Push Storage Service

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push
        run: |
          ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$ORG/storage-service
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE:$TAG -f build/docker/Dockerfile .
          docker push $IMAGE:$TAG
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Trigger deployment-chart
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository_owner }}/polycloud-helm
          event-type: update-storage
          client-payload: '{"tag": "${{ env.IMAGE_TAG }}"}'
